/**************************************************************************************************
*     File Name :                        MotorPara.c
*     Library/Module Name :              Motor
*     Author :                           CJYS
*     Create Date :                      2024/1/1
*     Abstract Description :             电机控制参数初始化源文件
**************************************************************************************************/
#include "MotorPara.h"

ST_MOTOR_TASK  Motor = 
{
    .LOOP_CTRL.Align_Ramp.Q32I_Init = MOTOR_ALIGNLOOP_RAMP_INIT,
    .LOOP_CTRL.Align_Ramp.Q32I_Target = MOTOR_ALIGNLOOP_RAMP_TARGET,
    .LOOP_CTRL.Align_Ramp.Q32I_ADDStep = MOTOR_ALIGNLOOP_RAMP_STEP,
    .LOOP_CTRL.Align_Ramp.Q32I_SUBStep = -MOTOR_ALIGNLOOP_RAMP_STEP,
    .LOOP_CTRL._P_Q32U_Align_Time1 = MOTOR_ALIGNLOOP_TIME1,
    .LOOP_CTRL._P_Q32U_Align_Time2 = MOTOR_ALIGNLOOP_TIME2,
    .LOOP_CTRL._P_Q32U_Align_Time3 = MOTOR_ALIGNLOOP_TIME3,
    
    .LOOP_CTRL._P_Q32U_Open_Min_Time = MOTOR_OPENLOOP_MIN_TIME,
    .LOOP_CTRL._P_F_Open_Switch_SRAD = MOTOR_OPENLOOP_SWITCH_SRAD,
    .LOOP_CTRL._P_Q32U_Open_Switch_Time = MOTOR_OPENLOOP_SWITCH_TIME,
    
    .LOOP_CTRL._P_F_Close1_Target_SRAD = MOTOR_CLOSELOOP1_TARGET_SRAD,
    .LOOP_CTRL._P_F_Close1_SRAD_Step = MOTOR_CLOSELOOP1_STEP,
    .LOOP_CTRL._P_F_Close1_Switch_SRAD = MOTOR_CLOSELOOP1_SWITCH_SRAD,
    .LOOP_CTRL._P_Q32U_Close1_Switch_Time = MOTOR_CLOSELOOP1_SWITCH_TIME,
    
    .LOOP_CTRL._P_F_Close2_Target_SRAD = MOTOR_CLOSELOOP2_SRAD_TARGET,
    .LOOP_CTRL._P_F_Close2_SRAD_Step = MOTOR_CLOSELOOP2_STEP,
        
    .IF_CTRL.Ramp_Iq.Q32I_Init = MOTOR_IF_IQRAMP_INIT,
    .IF_CTRL.Ramp_Iq.Q32I_Target = MOTOR_IF_IQRAMP_TARGET,
    .IF_CTRL.Ramp_Iq.Q32I_ADDStep = MOTOR_IF_IQRAMP_STEP,
    .IF_CTRL.Ramp_Iq.Q32I_SUBStep = -MOTOR_IF_IQRAMP_STEP,
    .IF_CTRL.Ramp_SRAD.Q32I_Init = MOTOR_IF_ANGLERAMP_INIT,
    .IF_CTRL.Ramp_SRAD.Q32I_Target = MOTOR_IF_ANGLERAMP_TARGET,
    .IF_CTRL.Ramp_SRAD.Q32I_ADDStep = MOTOR_IF_ANGLERAMP_STEP,
    .IF_CTRL.Ramp_SRAD.Q32I_SUBStep = -MOTOR_IF_ANGLERAMP_STEP,
    .IF_CTRL.Ramp_AngleERR.Q32I_ADDStep = MOTOR_VF_ANGLE_ERROR_RAMP_STEP,
    .IF_CTRL.Ramp_AngleERR.Q32I_SUBStep = -MOTOR_VF_ANGLE_ERROR_RAMP_STEP,
    .IF_CTRL._P_Q14I_Ts = Q14I_HTs_PU, 
    .IF_CTRL._P_Q14I_AngleERRLimit = MOTOR_VF_ANGLE_ERROR,
    
    .VF_CTRL.Ramp_Vq.Q32I_Init = MOTOR_VF_VQRAMP_INIT,
    .VF_CTRL.Ramp_Vq.Q32I_Target = MOTOR_VF_VQRAMP_TARGET,
    .VF_CTRL.Ramp_Vq.Q32I_ADDStep = MOTOR_VF_VQRAMP_STEP,
    .VF_CTRL.Ramp_Vq.Q32I_SUBStep = -MOTOR_VF_VQRAMP_STEP,
    .VF_CTRL.Ramp_SRAD.Q32I_Init = MOTOR_VF_ANGLERAMP_INIT,
    .VF_CTRL.Ramp_SRAD.Q32I_Target = MOTOR_VF_ANGLERAMP_TARGET,
    .VF_CTRL.Ramp_SRAD.Q32I_ADDStep = MOTOR_VF_ANGLERAMP_STEP,
    .VF_CTRL.Ramp_SRAD.Q32I_SUBStep = -MOTOR_VF_ANGLERAMP_STEP,
    .VF_CTRL.Ramp_AngleERR.Q32I_ADDStep = MOTOR_VF_ANGLE_ERROR_RAMP_STEP,
    .VF_CTRL.Ramp_AngleERR.Q32I_SUBStep = -MOTOR_VF_ANGLE_ERROR_RAMP_STEP,
    .VF_CTRL._P_Q14I_Ts = Q14I_HTs_PU,
    .VF_CTRL._P_Q14I_AngleERRLimit = MOTOR_VF_ANGLE_ERROR,
    
    .SVPWM_CTRL._P_Q12I_MaxDuty = (Q32I_)(HAL_MAX_DUTY*HAL_PWM_DUTY_MAX_F),
    .SVPWM_CTRL._P_Q12I_MinDuty = (Q32I_)(HAL_MIN_DUTY*HAL_PWM_DUTY_MAX_F),
    .SVPWM_CTRL._P_Q12I_ADCSampleDuty = (Q32I_)(HAL_ADC_SAMPLE_DUTY*HAL_PWM_DUTY_MAX_F),
    .SVPWM_CTRL._P_Q32I_Current_Scale = Q24I_CURRENT_SCALE_PU,
    .SVPWM_CTRL._P_Q12I_PWM_All_Count = HAL_PWM_ALL_COUNT_F,
    
    .SRAD_CTRL.PID_SRAD.Q14I_Kp = MOTOR_SPD_KP_GAIN,
    .SRAD_CTRL.PID_SRAD.Q14I_Ki = MOTOR_SPD_KI_GAIN,
    .SRAD_CTRL.PID_SRAD.Q14I_Kd = MOTOR_SPD_KD_GAIN,
    .SRAD_CTRL.PID_SRAD.Q14I_OutMax = MOTOR_SPD_PID_MAX,
    .SRAD_CTRL.PID_SRAD.Q14I_OutMin = MOTOR_SPD_PID_MIN,
    .SRAD_CTRL.PID_WEAK.Q14I_Kp = 0,
    .SRAD_CTRL.PID_WEAK.Q14I_Ki = 0,
    .SRAD_CTRL.PID_WEAK.Q14I_Kd = 0,
    .SRAD_CTRL.PID_WEAK.Q14I_OutMax = 0,
    .SRAD_CTRL.PID_WEAK.Q14I_OutMin = 0,
    .SRAD_CTRL.Ramp_SRAD.Q32I_Target = 0,
    .SRAD_CTRL.Ramp_SRAD.Q32I_ADDStep = MOTOR_CLOSELOOP2_STEP,
    .SRAD_CTRL.Ramp_SRAD.Q32I_SUBStep = -MOTOR_CLOSELOOP2_STEP,
    .SRAD_CTRL._P_Q14I_SRAD_Max =  Q14I_SRAD_MOTOR_TO_PU(MOTOR_MAX_SRAD),
    .SRAD_CTRL._P_Q14I_SRAD_Min = -Q14I_SRAD_MOTOR_TO_PU(MOTOR_MAX_SRAD),
    
    .CURRENT_CTRL.PID_Id.Q14I_Kp = MOTOR_FOC_KP_GAIN,
    .CURRENT_CTRL.PID_Id.Q14I_Ki = MOTOR_FOC_KI_GAIN,
    .CURRENT_CTRL.PID_Id.Q14I_Kd = MOTOR_FOC_KD_GAIN,
    .CURRENT_CTRL.PID_Iq.Q14I_Kp = MOTOR_FOC_KP_GAIN,
    .CURRENT_CTRL.PID_Iq.Q14I_Ki = MOTOR_FOC_KI_GAIN,
    .CURRENT_CTRL.PID_Iq.Q14I_Kd = MOTOR_FOC_KD_GAIN,
    .CURRENT_CTRL._P_Q14I_VsScale = MOTOR_VS_SCALE,

    .FLUX_CTRL.PID_PLL.Q14I_Kp = MOTOR_FLUX_PLL_KP,
    .FLUX_CTRL.PID_PLL.Q14I_Ki = MOTOR_FLUX_PLL_KI,
    .FLUX_CTRL.PID_PLL.Q14I_Kd = MOTOR_FLUX_PLL_KD,
    .FLUX_CTRL.PID_PLL.Q14I_OutMax = MOTOR_FLUX_PLL_MAX,
    .FLUX_CTRL.PID_PLL.Q14I_OutMin = MOTOR_FLUX_PLL_MIN,
    .FLUX_CTRL.FL_SRAD.Q08I_Filter_Coeff = USER_PLL_SPEED_LPF_COEFF,
    .FLUX_CTRL._P_Q14I_Ts = Q14I_HTs_PU,
    .FLUX_CTRL._P_Q14I_Gamma = MOTOR_FLUX_KT,
    .FLUX_CTRL._P_Q14I_Rs = Q14I_Rs_PU,
    .FLUX_CTRL._P_Q14I_Ld = Q14I_Ld_PU,
    .FLUX_CTRL._P_Q14I_Ls = Q14I_Ls_PU,
    .FLUX_CTRL._P_Q14I_Flux2 = Q32I_RHT_14(Q14I_FLUX_PU*Q14I_FLUX_PU),
    
    .SMO_CTRL.PID_PLL.Q14I_Kp = MOTOR_SMO_PLL_KP,
    .SMO_CTRL.PID_PLL.Q14I_Ki = MOTOR_SMO_PLL_KI,
    .SMO_CTRL.PID_PLL.Q14I_Kd = MOTOR_SMO_PLL_KD,
    .SMO_CTRL.PID_PLL.Q14I_OutMax = MOTOR_SMO_PLL_MAX,
    .SMO_CTRL.PID_PLL.Q14I_OutMin = MOTOR_SMO_PLL_MIN,
    .SMO_CTRL.FL_SRAD.Q08I_Filter_Coeff = USER_PLL_SPEED_LPF_COEFF,
    .SMO_CTRL._P_Q14I_Ts = Q14I_HTs_PU,
    .SMO_CTRL._P_Q14I_K1 = MOTOR_SMO_K1,
    .SMO_CTRL._P_Q14I_K2 = MOTOR_SMO_K2,
    .SMO_CTRL._P_Q14I_Rs = Q14I_Rs_PU,
    .SMO_CTRL._P_Q14I_Ld = Q14I_Ld_PU,
    .SMO_CTRL._P_Q14I_Lq = Q14I_Lq_PU,
    .SMO_CTRL._P_Q14I_One_Over_Ld = (Q32I_)(1.0f / MOTOR_Ld),
    .SMO_CTRL._P_Q14I_Rs_Over_Ld = (Q32I_)(MOTOR_Rs / MOTOR_Ld),
    .SMO_CTRL._P_Q14I_Ld_Lq_Over_Ld = (Q32I_)(1.0f - (MOTOR_Lq / MOTOR_Ld)),
    
};

